package org.locationtech.jtstest.testbuilder;

/**
 *
 * @author Bruno Silva
 */
public class MorphingGeometryControlPanel extends javax.swing.JPanel {

    /**
     * Creates new form MorphingGeometryControlPanel
     */
    public MorphingGeometryControlPanel() {
        initComponents();
        
        this.playBtn.setText(AppStrings.PLAY_STRING);
        this.saveAsBtn.setText(AppStrings.SAVE_AS_IMAGE_STRING);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        playBtn = new javax.swing.JButton();
        saveAsBtn = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        playBtn.setText("jButton1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        add(playBtn, gridBagConstraints);

        saveAsBtn.setText("jButton2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        add(saveAsBtn, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton playBtn;
    private javax.swing.JButton saveAsBtn;
    // End of variables declaration//GEN-END:variables
}
